CREATE TABLE MEMBER (
	MEMBER_CODE INT AUTO_INCREMENT PRIMARY KEY
	, MEMBER_ID VARCHAR(20) NOT NULL UNIQUE
	, MEMBER_PW VARCHAR(20) NOT NULL
	, MEMBER_NAME VARCHAR(20) NOT NULL
	, MEMBER_EMAIL VARCHAR(50) NOT NULL
	, MEMBER_TEL VARCHAR(50) NOT NULL
	, MEMBER_ADDR VARCHAR(50) NOT NULL
	, ADDR_DETAIL VARCHAR(50)
	, MEMBER_ROLL VARCHAR(20) DEFAULT 'USER' -- ADMIN
	, JOIN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FOOD_CATEGORY (
	CATE_CODE INT AUTO_INCREMENT PRIMARY KEY
	, CATE_NAME VARCHAR(50) NOT NULL
);


INSERT INTO FOOD_CATEGORY VALUES (1, 'COFFEE');
INSERT INTO FOOD_CATEGORY VALUES (2, 'NON-COFFE/TEA');
INSERT INTO FOOD_CATEGORY VALUES (3, 'ADE/JUCICE/BLENDED');
INSERT INTO FOOD_CATEGORY VALUES (4, 'DESSERT');

CREATE TABLE FOOD_INFO(
	FOOD_CODE INT AUTO_INCREMENT PRIMARY KEY
	, FOOD_NAME VARCHAR(50) NOT NULL
	, FOOD_PRICE INT NOT NULL
	, FOOD_INTRO VARCHAR(200) NOT NULL
	, REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, CATE_CODE INT NOT NULL REFERENCES food_category(CATE_CODE)
);

CREATE TABLE ITEM_IMAGE(
	IMG_CODE INT AUTO_INCREMENT PRIMARY KEY
	, ORIGIN_FILE_NAME VARCHAR(100) NOT NULL
	, ATTACHED_FILE_NAME VARCHAR(100) NOT NULL
	, FOOD_CODE INT NOT NULL REFERENCES FOOD_INFO (FOOD_CODE)
);

SELECT * FROM MEMBER;
SELECT *FROM food_category;
SELECT * FROM FOOD_INFO;
SELECT * FROM ITEM_IMAGE;