-- 기본키(PRIMARY KEY : PK)
-- NULL이 들어갈수 없고, 테이블 내에서 중복 불가

-- 회원 정보 테이블 
CREATE TABLE BOARD_MEMBER(
	-- 컬럼명 자료형 [제약조건](생략가능) 
	MEMBER_ID VARCHAR(20) PRIMARY KEY
	, MEMBER_PW VARCHAR(20) NOT NULL -- NULL X
	, MEMBER_NAME VARCHAR(20) NOT NULL
	, GENDER VARCHAR(2) -- '남' , '여'
	, MEMBER_EMAIL VARCHAR(30) UNIQUE -- UNIQUE(중복x) 	
	, IS_ADMIN VARCHAR(2) DEFAULT 'N' -- DEFAULT(기본값 설정) 관리자인지, 일반인인지 확인 'N', 'Y'
); 

SELECT * FROM board_member;

-- 게시글 정보 테이블

-- 테이블 자체 지우기 : DROP TABLE (테이블 명); - ROLLBACK 안됨. 정보가 아예 삭제.

-- WRITER : 외래키(Foreign key : Fk) 제약조건, 다른테이블의 데이터를 참조해서 정보를 넣겠다.
CREATE TABLE BOARD(
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY -- 입력하지 않아도 중복되지않게 1씩 증가
	, TITLE VARCHAR(30) NOT NULL
	, CONTENT VARCHAR(30) 
	, WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 날짜 데이터. CURRENT_TIMESTAMP(현재시간 현재 날짜를 넣어줌)
	, READ_CNT INT DEFAULT 0
);

CREATE TABLE COMMENT(
	COMMENT_NUM INT AUTO_INCREMENT PRIMARY KEY
	, COMMENT_WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, CONTENT VARCHAR(20) NOT NULL
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, BOARD_NUM INT REFERENCES board (BOARD_NUM)
);

SELECT * FROM COMMENT;
SELECT * FROM board;


INSERT INTO BOARD (TITLE, CONTENT, WRITER) 
VALUES ('AA', 'BB', NULL);

DELETE FROM BOARD;
DELETE FROM COMMENT;

COMMIT;

SELECT NOW() ; -- 현재시간을 보여줌. 

UPDATE BOARD_MEMBER
SET IS_ADMIN = 'Y'
WHERE MEMBER_ID = 'jhk7764';
COMMIT;

