-- 1번

CREATE TABLE MY_MEMBER(
	MEMBER_CODE INT PRIMARY KEY
	,	MEMBER_ID VARCHAR(10) NOT NULL
	,	MEMBER_PW VARCHAR(20) NOT NULL
	,	MEMBER_NAME VARCHAR(10) NOT NULL
	,	MEMBER_AGE INT 
	,	MEMBER_EMAIL VARCHAR(30)
);

SELECT * FROM MY_MEMBER;

-- 2번 
INSERT INTO MY_MEMBER VALUES (1, 'JAVA', '1234', '홍길동', 22 , 'aaa@naver.com');
INSERT INTO MY_MEMBER VALUES (2, 'NAVA', '2345', '김나비', 18 , 'baa@naver.com');
INSERT INTO MY_MEMBER VALUES (3, 'HONG', '4567', '김길동', 35 , 'zxa@naver.com');
INSERT INTO MY_MEMBER VALUES (4, 'AAAA', '1235', '이제동', 24 , 'asd@naver.com');
INSERT INTO MY_MEMBER VALUES (5, 'BBB1', '1745', '소지우', 21 , 'zda@naver.com');

DELETE FROM my_member;

-- 3번 
UPDATE my_member
SET MEMBER_NAME = '김자바'
	,MEMBER_ID = 'KIMJAVA'
WHERE MEMBER_CODE = 1;

-- 4번 

SELECT * FROM emp;
SELECT * FROM dept;

SELECT EMPNO
	, ENAME
	, SAL
	, COMM
FROM emp
WHERE (SAL >= 500 AND SAL <= 3000);

-- 5번
SELECT EMPNO
	, ENAME	
	, HIREDATE
FROM emp
WHERE (ENAME LIKE '%김%' OR ENAME LIKE '__기')
ORDER BY EMPNO DESC;  

-- 6번

SELECT EMPNO
	, ENAME
	, DEPTNO
	, CASE 
	  WHEN DEPTNO = 10 THEN '인사부'
	  WHEN DEPTNO = 20 THEN '영업부'
	  WHEN DEPTNO = 30 THEN '개발부'
	  ELSE '생산부'
	  END AS DNAME
FROM emp;

-- 7번

SELECT EMPNO
	, ENAME
	, DATE_FORMAT(HIREDATE, '%m') HIREDATE
	, IFNULL(COMM , 0) COMM
FROM emp
WHERE DATE_FORMAT(HIREDATE, '%m') = '01'
ORDER BY HIREDATE;

-- 8번

SELECT SUM(SAL) AS SAL_SUM
	,	AVG(SAL)	AS SAL_AVG
	,	AVG(COMM) AS COMM
	, JOB
FROM emp
GROUP BY JOB	
ORDER BY SAL_SUM DESC;

-- 9번

SELECT EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, DEPTNO
	, (SELECT 
			DNAME 
			FROM DEPT 
			WHERE emp.DEPTNO = DEPTNO) DNAME
FROM emp
WHERE DEPTNO = (SELECT DEPTNO FROM dept WHERE DNAME = '인사부');

-- 10번
SELECT EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, D.DEPTNO
	, DNAME
FROM emp E INNER JOIN dept D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = '인사부'
AND SAL >= 500
ORDER BY EMPNO DESC , ENAME ASC;