
CREATE TABLE car_info (
	CAR_NUM INT AUTO_INCREMENT
	, MODEL_NAME VARCHAR(50) NOT NULL
	, PRICE INT NOT NULL
	, MADE_BY VARCHAR(50) NOT NULL
	, CONSTRAINT CAR_INFO_PK PRIMARY KEY (CAR_NUM)
);
-- car_info 테이블에서 car_num이 1인 데이터 삭제

DELETE FROM car_info
WHERE CAR_NUM > 5;
COMMIT;
 
SELECT * FROM SALES_info;

INSERT INTO car_info VALUES (1, 'A', 1000, 'KOR');
INSERT INTO SALES_info VALUES (2, 'A', '010','RED', NOW()  ,1);
COMMIT;

DROP TABLE sales_info;

CREATE TABLE sales_info (
	SALES_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BUYETR VARCHAR(50) NOT NULL
	, TEL VARCHAR(50)
	, COLOR VARCHAR(50) NOT NULL
	, SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, CAR_NUM INT NOT NULL
	, CONSTRAINT CAR_SALES_FK FOREIGN KEY (CAR_NUM)
	  REFERENCES car_info(CAR_NUM) ON DELETE CASCADE
); 

 SELECT SALES_NUM
        ,BUYETR
        ,TEL
        ,COLOR
        ,SALES_DATE
        ,MODEL_NAME
        ,PRICE
        ,CAR.CAR_NUM
        FROM SALES_INFO SAL INNER JOIN CAR_INFO CAR
        ON SAL.CAR_NUM = CAR.CAR_NUM;
        
        
        
SELECT * FROM CICI
WHERE SERIAL_NO = 'ICW0W2100497';

SELECT DECIBEL
  , DECIBEL_TIME
  FROM decibel_info
  WHERE SERIAL_NO = 'ICW0W2100497'
  AND DECIBEL_TIME= (SELECT MAX(DECIBEL_TIME) FROM DECIBEL_INFO WHERE SERIAL_NO = 'ICW0W2100497');