 -- 파이썬 데이터 테이블
DROP TABLE map; 
DROP TABLE cici;
DROP TABLE decibel_info;
DROP TABLE air_quality;
DROP TABLE temandhum;

-- 위도 , 경도 테이블 
CREATE TABLE MAP(
	SERIAL_NO VARCHAR(15) NOT NULL PRIMARY KEY
	, STATION_NAME VARCHAR(20) NOT NULL
	, IAT DOUBLE DEFAULT 37.0000
	, ION DOUBLE DEFAULT 126.0000
);

ALTER TABLE MAP CHANGE ION LON DOUBLE DEFAULT 126.0000;
COMMImapT;

SELECT DATA_CODE
, HOUR(DATE_TIME) DATE_TIME
, MAX(TEMPERATURE) TEMPERATURE
, MAX(HUMIDITY) HUMIDITY
, MIN(TEMPERATURE) MINTEMPERATURE 
, MIN(HUMIDITY) MINHUMIDITY
, DATE_TIME
FROM temandhum
WHERE DATE_FORMAT(DATE_TIME, '%Y-%m-%d %h') 
= DATE_FORMAT(NOW(), '%Y-%m-%d 09');

SELECT DATA_CODE
, HOUR(DATE_TIME)DATE_TIME
, MAX(TEMPERATURE) TEMPERATURE
, MAX(HUMIDITY) HUMIDITY
, MIN(TEMPERATURE) MINTEMPERATURE 
, MIN(HUMIDITY) MINHUMIDITY
FROM temandhum
WHERE DATE_FORMAT(DATE_TIME, '%Y-%m-%d %h') 
= DATE_FORMAT(NOW(), '%Y-%m-%d 11');

SELECT DATA_CODE
, HOUR(DATE_TIME)DATE_TIME
, MAX(TEMPERATURE) TEMPERATURE
, MAX(HUMIDITY) HUMIDITY
, MIN(TEMPERATURE) MINTEMPERATURE 
, MIN(HUMIDITY) MINHUMIDITY
FROM temandhum
WHERE DATE_FORMAT(DATE_TIME, '%Y-%m-%d %H') 
= DATE_FORMAT(NOW(), '%Y-%m-%d 13');

SELECT DATE_FORMAT(NOW(), '%Y-%m-%d %H');

SELECT DATA_CODE
, DATE_TIME
, MAX(TEMPERATURE) TEMPERATURE
, MAX(HUMIDITY) HUMIDITY
, MIN(TEMPERATURE) MINTEMPERATURE 
, MIN(HUMIDITY) MINHUMIDITY
FROM temandhum
WHERE DATE_FORMAT(DATE_TIME, '%Y-%m-%d %h') 
= DATE_FORMAT(NOW(), '%Y-%m-%d 15');

SELECT DATA_CODE
, DATE_TIME
, MAX(TEMPERATURE) TEMPERATURE
, MAX(HUMIDITY) HUMIDITY
, MIN(TEMPERATURE) MINTEMPERATURE 
, MIN(HUMIDITY) MINHUMIDITY
FROM temandhum
WHERE DATE_FORMAT(DATE_TIME, '%Y-%m-%d %h') 
= DATE_FORMAT(NOW(), '%Y-%m-%d 17');

-- 서초구 온습도 테이블 
CREATE TABLE TEMANDHUM (
	DATA_CODE INT AUTO_INCREMENT PRIMARY KEY
	, DATE_TIME DATETIME NOT NULL
	, SERIAL_NO VARCHAR(20) REFERENCES MAP(SERIAL_NO)
	, TEMPERATURE DOUBLE NOT NULL
	, HUMIDITY INT NOT NULL
);
ALTER TABLE AIR_QUALITY ADD COLUMN AIR_TIME DATETIME NOT NULL AFTER VOCS_CODE;
ALTER TABLE CICI ADD COLUMN CICI_TIME DATETIME NOT NULL AFTER CICI_GRADE;

SELECT DATA_CODE
	, TEMPERATURE
	, HUMIDITY
	, DATE_TIME
	, SERIAL_NO
FROM TEMANDHUM
WHERE SERIAL_NO = 'ICW0W2100491'
AND DATE_FORMAT(DATE_TIME,'%Y%m%d %h') = DATE_FORMAT(NOW(), '%Y%m%d %h');


SELECT SUBSTRING(NOW(),1,13);

SELECT DATA_CODE
	, TEMPERATURE
	, HUMIDITY
	, MAX(DATE_TIME)
	, SERIAL_NO
FROM TEMANDHUM
WHERE SERIAL_NO = 'ICW0W2100491'
AND DATE_FORMAT(DATE_TIME,'%Y%m%d %h') = DATE_FORMAT(NOW(), INTERVAL 1 HOUR), '%Y%m%d %h');

SELECT * FROM temandhum;
SELECT MAX(DATE_TIME) FROM temandhum;

SELECT * FROM temandhum
WHERE SERIAL_NO = 'ICW0W2100491'
AND DATE_TIME = (SELECT MAX(DATE_TIME) FROM temandhum);

SELECT DATA_CODE
        , TEMPERATURE
        , HUMIDITY
        , DATE_TIME
        , SERIAL_NO
FROM TEMANDHUM
WHERE SERIAL_NO = 'ICW0W2100562'
AND DATE_TIME = (SELECT MAX(DATE_TIME) FROM temandhum WHERE SERIAL_NO = 'ICW0W2100562' );

SELECT DECIBEL
	, DECIBEL_TIME
FROM decibel_info
WHERE SERIAL_NO = 'ICW0W2100562'
AND DECIBEL_TIME= (SELECT MAX(DECIBEL_TIME) FROM DECIBEL_INFO WHERE SERIAL_NO = 'ICW0W2100562');

DELETE FROM MAP
WHERE SERIAL_NO NOT IN (SELECT DISTINCT SERIAL_NO FROM AIR_QUALITY);

COMMIT;

SELECT * FROM MAP;

-- 서초구 각 위치의 데시벨 데이터
CREATE TABLE DECIBEL_INFO(
   DECIBEL_CODE INT AUTO_INCREMENT PRIMARY KEY
   , DECIBEL INT NOT NULL
   , DECIBEL_TIME DATETIME NOT NULL
   , DECIBEL_GRADE VARCHAR(10) NOT NULL DEFAULT '보통' -- '좋음, 보통, 나쁨'
   , SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);

-- 실내 공기(미세먼지, 초미세먼지, 실내지수)
CREATE TABLE air_quality (
	AIR_NO INT AUTO_INCREMENT PRIMARY KEY
	, PM_CODE INT NOT NULL
	, PM_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, FPM_CODE INT NOT NULL
	, FPM_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, CO2_CODE FLOAT NOT NULL
	, VOCS_CODE INT NOT NULL
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);
SELECT * FROM air_quality;
-- 실내통합지수
CREATE TABLE cici (
	CICI_NO  INT AUTO_INCREMENT PRIMARY KEY
	, CICI_CODE INT NOT NULL
	, CICI_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);

SELECT * FROM DECIBEL_INFO;



IF((SELECT DATE_TIME FROM temandhum WHERE SUBSTRING(DATE_TIME,1,13) = SUBSTRING(NOW(),1,13)) IS NOT NULL
,SELECT DATA_CODE
	, TEMPERATURE
	, HUMIDITY
	, DATE_TIME
	, SERIAL_NO
FROM TEMANDHUM
WHERE SERIAL_NO = 'ICW0W2100491'
AND DATE_FORMAT(DATE_TIME,'%Y%m%d %h') = DATE_FORMAT(NOW(), '%Y%m%d %h');
,SELECT DATA_CODE
	, TEMPERATURE
	, HUMIDITY
	, DATE_TIME
	, SERIAL_NO
FROM TEMANDHUM
WHERE SERIAL_NO = 'ICW0W2100491'
AND DATE_FORMAT(DATE_TIME,'%Y%m%d %h') = DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 1 HOUR), '%Y%m%d %h');

)



