CREATE TABLE MAP(
	SERIAL_NO VARCHAR(15) NOT NULL PRIMARY KEY
	, STATION_NAME VARCHAR(20) NOT NULL
	, LAT DOUBLE DEFAULT 37.0000
	, LON DOUBLE DEFAULT 126.0000
);

SELECT * FROM map;

CREATE TABLE DECIBEL_INFO(
	DECIBEL_CODE INT AUTO_INCREMENT PRIMARY KEY
	, DECIBEL INT NOT NULL
	, DECIBEL_TIME DATETIME NOT NULL
	, DECIBEL_GRADE VARCHAR(10) NOT NULL DEFAULT '보통' -- '좋음, 보통, 나쁨'
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);

DROP TABLE air_quality;

-- 실내 공기
CREATE TABLE air_quality (
	AIR_NO INT AUTO_INCREMENT PRIMARY KEY
	, PM_CODE INT NOT NULL
	, PM_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, FPM_CODE INT NOT NULL
	, FPM_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, CO2_CODE FLOAT NOT NULL
	, VOCS_CODE INT NOT NULL
	, AIR_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);

CREATE TABLE CICI (
	CICI_NO INT AUTO_INCREMENT PRIMARY KEY
	, CICI_CODE INT NOT NULL
	, CICI_GRADE VARCHAR(10) DEFAULT '보통' -- 좋음, 보통, 나쁨, 매우 나쁨
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
	, CICI_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE cici;

CREATE TABLE TEMANDHUM(
	DATA_CODE INT AUTO_INCREMENT PRIMARY KEY
	, DATE_TIME DATETIME NOT NULL
	, TEMPERATURE FLOAT NOT NULL
	, HUMIDITY INT NOT NULL
	, SERIAL_NO VARCHAR(15) REFERENCES MAP (SERIAL_NO)
);